### ISSUE TITLE
Set zoom to fit to window not working as in sxiv

### ISSUE THREAD

**Issue by minzanupam** [eylles/rxiv#12]
How do I start, when you set an image to fit to window. It set the zoom level according to that image and does not change when the image is changed.
Say for example I have a 4k image and another 720p one, I opened both of them rxiv *,
when I set zoom level to fit the window (W) and go to the next image (n), the 720p one will be zoom out (i.e appear smaller than the window size), and vice-versa which is does not happen in sxiv.
I would love to help, but I am not that knowledgeable in that regard.

**Comment by Dhruv-Vanjari** [comment]
Hi,

Thanks for reporting this issue,

I think the last commit 8d99e9a32fed66e43b5f178467727377ce45c2c3 have caused this issue. It is strange that sxiv does not use the img_zoom function for fit win operations, rather it manually overrides the zoom property and updates the required flags. I will revert the changes and merge new changes when they are stable. Thanks :)
